text = "belajar python dasar"

print(text.capitalize())
print(text.title())
print(text.upper())
print(text.lower())
print(text.casefold())
print(text.swapcase())
print(text.center(10))
print(text.center(10, '-'))
print(text.replace('a', 'e'))
print(text.split(' '))
print(text.partition(' '))
print(text.count(' '))
print(text.encode())
print(text.endswith())
print(text.find(' '))
print(text.index(' '))
print(text.index(' ', 2, 5))
print(text.strip())
print(text.lstrip())
print(text.rstrip())
sisip = "+"
print(sisip.join(text))
print(text.isalnum())
print(text.isalpha())
print(text.isdecimal())
print(text.isdigit())
print(text.isidentifier())
print(text.islower())
print(text.isupper())
print(text.isnumeric())
print(text.isspace())
print(text.istitle())